routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Route::middleware(['auth:sanctum', 'verified', 'isAdmin'])->resource('users', UserController::class)->except([
    'create', 'show'
]);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;
use App\Presenters\UserPresenter;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;
    use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];

    /**
     * Relationship with their
     * assigned tasks
     */
    public function tasks()
    {
        return $this->hasMany(Task::class, 'assigned_id');
    }


    /**
     * Relationship with their
     * created tasks
     */
    public function createdTasks()
    {
        return $this->hasMany(Task::class, 'creator_id');
    }

    public function presenter()
    {
        return new UserPresenter($this);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Laravel\Fortify\Rules\Password;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Auth;


class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('users.index', [
            'users' => User::paginate()
        ]);
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Validator::make($request->all(), [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', new Password, 'confirmed'],
        ])->validate();

        User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request->password)
        ]);

        return redirect()->route('users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('users.show', [
            'user' => $user
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('users.edit', [
            'user' => $user
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $request->validate([
            'name' => 'required|string',
            'email' => 'required|email|max:255|unique:users,email,'.$user->id.',id',
            'password' => 'nullable|confirmed'
        ]);

        $user->name = $request->name;
        $user->email = $request->email;
        if ($request->filled('password'))
        {
            $user->forceFill([
                'password' => Hash::make($request->password),
            ])->save();
        }

        $user->save();

        return redirect()->route('users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        if ($user->id == 1)
        {
            abort(403);
        }
        
        $user->delete();

        return redirect()->route('users.index');
    }
}

app/Http/Livewire/User/RoleToggle.php
<?php

namespace App\Http\Livewire\User;

use Livewire\Component;
use Spatie\Permission\Models\Role;
use App\Models\User;
use Illuminate\Support\Facades\Auth;

class RoleToggle extends Component
{
    public $user;

    public function mount(User $user)
    {
        $this->fill(['user' => $user]);
    }

    public function render()
    {
        return view('livewire.user.role-toggle', [
            'roles' => $this->getRoles()
        ]);
    }

    private function getRoles()
    {
        return Role::get();
    }

    public function toggleRole(string $role)
    {
        if (!Auth::user()->hasRole('administrator') || $this->user->id == 1)
        {
            return ;
        }
        if ($this->user->hasRole($role))
        {
            $this->user->removeRole($role);
        }
        else
        {
            $this->user->assignRole($role);
        }
    }
}

app/Http/Livewire/User/UserSelect.php
<?php

namespace App\Http\Livewire\User;

use Livewire\Component;
use App\Models\User;
use Illuminate\Support\Facades\Auth;

class UserSelect extends Component
{

    public $userId;

    public function mount()
    {
        $this->fill(['userId' => Auth::id()]);
    }

    public function render()
    {
        return view('livewire.user.user-select', [
            'users' => $this->getUsers()
        ]);
    }

    private function getUsers()
    {
        return User::select('id', 'name')->get();
    }

    public function selectUser(int $userId)
    {
        $this->emitUp('userSelected', $userId);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/users/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Users') }} > {{ $user->name }}
        </h2>
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <form action="{{ route('users.update', ['user' => $user->id]) }}" method="POST" id="edit" name="edit">
                    @csrf()
                    @method('PUT')
                    <div class="shadow sm:rounded-md sm:overflow-hidden">
                        <div class="px-4 py-5 bg-white space-y-6 sm:p-6">
                            <div class="grid grid-cols-4 gap-6">
                                <div class="col-span-4 sm:col-span-2">
                                    <label for="company_website" class="block text-sm font-medium text-gray-700">
                                        {{ __('Name') }}
                                    </label>
                                    <div class="mt-1 flex rounded-md shadow-sm">
                                        <input type="text" name="name" id="name" class="focus:ring-indigo-500 focus:border-indigo-500 flex-1 block w-full rounded-md sm:text-sm border-gray-300" placeholder="{{ __('Name') }}" value="{{ $user->name }}">
                                        @error('name')
                                        <span class="flex items-center font-medium tracking-wide text-red-500 text-xs mt-1 ml-1">
                                            {{ $message }}        
                                        </span>
                                    @enderror
                                    </div>
                                </div>
                                <div class="col-span-4 sm:col-span-2">
                                    <label for="company_website" class="block text-sm font-medium text-gray-700">
                                        {{ __('Email') }}
                                    </label>
                                    <div class="mt-1 rounded-md shadow-sm">
                                        <input type="email" name="email" id="email" class="focus:ring-indigo-500 focus:border-indigo-500 flex-1 block w-full rounded-md sm:text-sm border-gray-300" placeholder="{{ __('Email') }}" value="{{ $user->email }}">
                                        @error('email')
                                            <span class="flex items-center font-medium tracking-wide text-red-500 text-xs mt-1 ml-1">
                                                {{ $message }}        
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-span-4 sm:col-span-2">
                                    <label for="company_website" class="block text-sm font-medium text-gray-700">
                                        {{ __('Password') }}
                                    </label>
                                    <div class="mt-1 rounded-md shadow-sm">
                                        <input name="password" id="password" type="password" class="focus:ring-indigo-500 focus:border-indigo-500 flex-1 block w-full rounded-md sm:text-sm border-gray-300" placeholder="{{ __('New password') }}">
                                        @error('password')
                                            <span class="flex items-center font-medium tracking-wide text-red-500 text-xs mt-1 ml-1">
                                                {{ $message }}        
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-span-4 sm:col-span-2">
                                    <label for="company_website" class="block text-sm font-medium text-gray-700">
                                        {{ __('Confirm password') }}
                                    </label>
                                    <input name="password_confirmation" id="password_confirmation" type="password" class="focus:ring-indigo-500 focus:border-indigo-500 flex-1 block w-full rounded-md sm:text-sm border-gray-300" placeholder="{{ __('Confirm new password') }}">
                                    <div class="mt-1 flex rounded-md shadow-sm">
                                    </div>
                                </div>
                            </div>
                            <div>
                                <livewire:user.role-toggle :user="$user">
                                </livewire:user.role-toggle>
                            </div>
               
                        </div>
                    </div>
                </form>
                <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
                    @if($user->id != 1)
                        <form action="{{ route('users.destroy', ['user' => $user->id]) }}" method="POST" id="delete" name="delete">
                            @csrf()
                            @method('DELETE')
                            <button type="submit" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500" form="delete">
                                {{ __('Delete') }}
                            </button>
                        </form>
                    @endif
                    <button type="submit" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" form="edit">
                        {{ __('Save') }}
                    </button>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/users/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Users') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                      <tr>
                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            {{ __('Name') }}
                        </th>
                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            {{ __('Roles') }}
                        </th>
                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            {{ __('Email verified') }} 
                        </th>
                        <th scope="col" class="relative px-6 py-3">
                          <span class="sr-only">Edit</span>
                        </th>
                      </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-gray-200">
                        @foreach ($users as $user)
                            <tr>
                                <td class="px-6 py-4 whitespace-nowrap">
                                <div class="flex items-center">
                                    <div class="flex-shrink-0 h-10 w-10">
                                        <img class="h-10 w-10 rounded-full" src="{{ $user->profilePhotoUrl }}" alt="">
                                    </div>
                                    <div class="ml-4">
                                        <div class="text-sm font-medium text-gray-900">
                                            {{ $user->name }}
                                        </div>
                                        <div class="text-sm text-gray-500">
                                            {{ $user->email }}
                                        </div>
                                    </div>
                                </div>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    {{ $user->presenter()->roles() }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    @if($user->email_verified_at)
                                        <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                                            {{ __('Yes') }}
                                        </span>
                                    @else
                                        <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-red-100 text-red-800">
                                            {{ __('No') }}
                                        </span>
                                    @endif
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                    <a href="{{ route('users.edit', ['user' => $user->id]) }}" class="text-indigo-600 hover:text-indigo-900">Edit</a>
                                </td>
                            </tr>
                        @endforeach
          
                            
                    </tbody>
                </table>
                <div class="bg-white px-4 py-3 border-t border-gray-200 sm:px-6">
                    {{ $users->links() }}
                </div>
            </div>
            <form action="{{ route('users.store') }}" method="POST">
                @csrf()
                <div class="shadow sm:rounded-md sm:overflow-hidden  mt-6">
                    <div class="px-4 py-5 bg-white space-y-6 sm:p-6">
                        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                            {{ __('Create') }}
                        </h2>
                        <div class="grid grid-cols-4 gap-6">
                            <div class="col-span-4 sm:col-span-2">
                                <label for="company_website" class="block text-sm font-medium text-gray-700">
                                    {{ __('Name') }}
                                </label>
                                <div class="mt-1 flex rounded-md shadow-sm">
                                    <input type="text" name="name" id="name" class="focus:ring-indigo-500 focus:border-indigo-500 flex-1 block w-full rounded-md sm:text-sm border-gray-300" placeholder="{{ __('Name') }}" required  required value="{{ old('name') }}">
                                    @error('name')
                                    <span class="flex items-center font-medium tracking-wide text-red-500 text-xs mt-1 ml-1">
                                        {{ $message }}        
                                    </span>
                                @enderror
                                </div>
                            </div>
                            <div class="col-span-4 sm:col-span-2">
                                <label for="company_website" class="block text-sm font-medium text-gray-700">
                                    {{ __('Email') }}
                                </label>
                                <div class="mt-1 rounded-md shadow-sm">
                                    <input type="email" name="email" id="email" class="focus:ring-indigo-500 focus:border-indigo-500 flex-1 block w-full rounded-md sm:text-sm border-gray-300" placeholder="{{ __('Email') }}" required value="{{ old('email') }}">
                                    @error('email')
                                        <span class="flex items-center font-medium tracking-wide text-red-500 text-xs mt-1 ml-1">
                                            {{ $message }}        
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-span-4 sm:col-span-2">
                                <label for="company_website" class="block text-sm font-medium text-gray-700">
                                    {{ __('Password') }}
                                </label>
                                <div class="mt-1 rounded-md shadow-sm">
                                    <input name="password" id="password" type="password" class="focus:ring-indigo-500 focus:border-indigo-500 flex-1 block w-full rounded-md sm:text-sm border-gray-300" placeholder="{{ __('New password') }}">
                                    @error('password')
                                        <span class="flex items-center font-medium tracking-wide text-red-500 text-xs mt-1 ml-1">
                                            {{ $message }}        
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-span-4 sm:col-span-2">
                                <label for="company_website" class="block text-sm font-medium text-gray-700">
                                    {{ __('Confirm password') }}
                                </label>
                                <input name="password_confirmation" id="password_confirmation" type="password" class="focus:ring-indigo-500 focus:border-indigo-500 flex-1 block w-full rounded-md sm:text-sm border-gray-300" placeholder="{{ __('Confirm new password') }}" required>
                                <div class="mt-1 flex rounded-md shadow-sm">
                                </div>
                            </div>
                        </div>
                            <button type="submit" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                                {{ __('Create') }}
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</x-app-layout>